<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE glsa SYSTEM "http://www.gentoo.org/dtd/glsa.dtd">

<glsa id="200903-11">
  <title>PyCrypto: Execution of arbitrary code</title>
  <synopsis>
    A buffer overflow in PyCrypto might lead to the execution of arbitrary code
    when decrypting using ARC2.
  </synopsis>
  <product type="ebuild">pycrypto</product>
  <announced>March 09, 2009</announced>
  <revised>March 09, 2009: 01</revised>
  <bug>258049</bug>
  <access>remote</access>
  <affected>
    <package name="dev-python/pycrypto" auto="yes" arch="*">
      <unaffected range="ge">2.0.1-r8</unaffected>
      <vulnerable range="lt">2.0.1-r8</vulnerable>
    </package>
  </affected>
  <background>
    <p>
    PyCrypto is the Python Cryptography Toolkit.
    </p>
  </background>
  <description>
    <p>
    Mike Wiacek of the Google Security Team reported a buffer overflow in
    the ARC2 module when processing a large ARC2 key length.
    </p>
  </description>
  <impact type="normal">
    <p>
    A remote attacker could entice a user or automated system to decrypt an
    ARC2 stream in an application using PyCrypto, possibly resulting in the
    execution of arbitrary code or a Denial of Service.
    </p>
  </impact>
  <workaround>
    <p>
    There is no known workaround at this time.
    </p>
  </workaround>
  <resolution>
    <p>
    All PyCrypto users should upgrade to the latest version:
    </p>
    <code>
    # emerge --sync
    # emerge --ask --oneshot --verbose &quot;&gt;=dev-python/pycrypto-2.0.1-r8&quot;</code>
  </resolution>
  <references>
    <uri link="http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2009-0544">CVE-2009-0544</uri>
  </references>
  <metadata tag="requester" timestamp="Sat, 07 Mar 2009 16:35:09 +0000">
    rbu
  </metadata>
  <metadata tag="submitter" timestamp="Sat, 07 Mar 2009 18:22:46 +0000">
    rbu
  </metadata>
  <metadata tag="bugReady" timestamp="Sat, 07 Mar 2009 18:24:44 +0000">
    rbu
  </metadata>
</glsa>
